### ISSUE TITLE
can't install sarah in fedora 23

### ISSUE THREAD

**Issue by Wael-Fadlallah0** [semicode-ltd/sarah#17]
![screenshot from 2016-12-20 15-00-33](https://cloud.githubusercontent.com/assets/24671982/21349829/26c6724a-c6c5-11e6-99a1-906519ce1a91.png)

**Comment by semicode-ltd** [comment]
okay try to cd bin and then use the export values ;)

**Comment by Wael-Fadlallah0** [comment]
I didn't get it , what is "export values" !! explain more ?

**Comment by semicode-ltd** [comment]
Okay do as following : 
cd sarah-master/
make 
make install 
cd bin/
export LD_LIBRARY_PATH=. 
export GI_TYPELIB_PATH=.
./sarah

note : you may get some warning because many plugins are not competed we still re-writing them

**Comment by semicode-ltd** [comment]
the only working plugins for now is hi and vala-extension-demo so you can also remove the other plugins :)

**Comment by Wael-Fadlallah0** [comment]
it doesn't work fine for me (I did remove all the other plugins ) , I guess I shall wait for you to fix it 

all the best 👍

**Comment by semicode-ltd** [comment]
okay let me check :)

**Comment by semicode-ltd** [comment]
we fixed the issue try again and run : 
sudo dnf install libpeas-*
first
