### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by nikssardana** [semicode-ltd/sarah#20]
Hi
I tried to install sarah on my Ubuntu machine using the steps mentioned in the readme. However, I can't install it. 

Python and other dependencies were installed successfully using apt-get and pip.

The output of "make" command is:
`valac -o libsarah.so --library=sarah -H ./bin/sarah.h  --gir=Sarah-1.0.gir -X -shared -X  -fPIC  --pkg libpeas-1.0  --pkg gmodule-2.0  sarah.vala  -d ./bin
/home/niks/Downloads/sarah/sarah-master/bin/sarah.vala.c: In function ‘sarah_core_list’:
/home/niks/Downloads/sarah/sarah-master/bin/sarah.vala.c:273:9: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  _tmp1_ = peas_engine_get_plugin_list (_tmp0_);
         ^
/home/niks/Downloads/sarah/sarah-master/bin/sarah.vala.c:314:24: warning: '#' flag used with ‘%s’ gnu_printf format [-Wformat=]
      fprintf (_tmp10_, "%#s \t %#s\n", _tmp12_, _tmp14_);
                        ^
/home/niks/Downloads/sarah/sarah-master/bin/sarah.vala.c:314:24: warning: '#' flag used with ‘%s’ gnu_printf format [-Wformat=]
/home/niks/Downloads/sarah/sarah-master/bin/sarah.vala.c: In function ‘sarah_app_init’:
/home/niks/Downloads/sarah/sarah-master/bin/sarah.vala.c:525:63: warning: passing argument 3 of ‘_vala_string_array_contains’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
    if (_vala_string_array_contains (_tmp13_, _tmp13__length1, _tmp12_)) {
                                                               ^
/home/niks/Downloads/sarah/sarah-master/bin/sarah.vala.c:464:17: note: expected ‘gchar * {aka char *}’ but argument is of type ‘const gchar * {aka const char *}’
 static gboolean _vala_string_array_contains (gchar** stack, int stack_length, gchar* needle) {
                 ^
g-ir-compiler --shared-library=libsarah.so ./bin/Sarah-1.0.gir -o ./bin/Sarah-1.0.typelib
valac  -o sarah  main.vala -b .  --vapidir ./bin --pkg libpeas-1.0  --pkg sarah   -X -I./bin -X -L./bin -X  -lsarah -d ./bin
valac -o libhello.so --library=hello  ./plugins/vala-extension-demo/vala-extension.vala  -X -shared -X -fPIC   --vapidir ./bin --pkg sarah  --pkg libpeas-1.0  -X -I./bin -X -L./bin -X -lsarah -d ./bin/plugins/vala-extension-demo/
`

And the output of "make install" command is:
`cp  -rf ./plugins/*  ./bin/plugins/
cd ./bin`

**Comment by semicode-ltd** [comment]
there isw nothing wrong friend this is just warnings so just complete the steps in the README file but switch to the bin folder first before doing ./sarah

**Comment by nikssardana** [comment]
Hey

I tried it and ran 
`  sarah first python`

But it shows this error:
`
./sarah: error while loading shared libraries: libsarah.so: cannot open shared object file: No such file or directory
`

**Comment by semicode-ltd** [comment]
do : 
export LD_LIBRARY_PATH=.
export GI_TYPELIB_PATH=.
and try : ./sarah hi
first plugin is not completed or check the current completed plugins using the command : 
./sarah list

**Comment by nikssardana** [comment]
Hey
I did as you mentioned. Still no plugin is working.
./sarah list gave me the following output:
`
(process:4655): libpeas-WARNING **: Could not find 'Module' in '[Plugin]' section in './plugins/youtube/youtube.plugin'

(process:4655): libpeas-WARNING **: Error loading './plugins/youtube/youtube.plugin'

(process:4655): libpeas-WARNING **: Could not find 'Module' in '[Plugin]' section in './plugins/first/first.plugin'

(process:4655): libpeas-WARNING **: Error loading './plugins/first/first.plugin'

(process:4655): libpeas-WARNING **: Could not find 'Module' in '[Plugin]' section in './plugins/howdoi/howdoi.plugin'

(process:4655): libpeas-WARNING **: Error loading './plugins/howdoi/howdoi.plugin'

(process:4655): libpeas-WARNING **: Could not find 'Module' in '[Plugin]' section in './plugins/whois/whois.plugin'

(process:4655): libpeas-WARNING **: Error loading './plugins/whois/whois.plugin'

(process:4655): libpeas-WARNING **: Could not find 'Module' in '[Plugin]' section in './plugins/google/google.plugin'

(process:4655): libpeas-WARNING **: Error loading './plugins/google/google.plugin'

(process:4655): libpeas-WARNING **: Could not find 'Module' in '[Plugin]' section in './plugins/watch/watch.plugin'

(process:4655): libpeas-WARNING **: Error loading './plugins/watch/watch.plugin'

(process:4655): libpeas-WARNING **: Could not find 'Module' in '[Plugin]' section in './plugins/time/time.plugin'

(process:4655): libpeas-WARNING **: Error loading './plugins/time/time.plugin'

(process:4655): libpeas-WARNING **: Could not find 'Module' in '[Plugin]' section in './plugins/github/github.plugin'

(process:4655): libpeas-WARNING **: Error loading './plugins/github/github.plugin'

(process:4655): libpeas-WARNING **: Could not find 'Module' in '[Plugin]' section in './plugins/speedtest/speedtest.plugin'

(process:4655): libpeas-WARNING **: Error loading './plugins/speedtest/speedtest.plugin'
Commands :
hi 	 python hi plugins
hello 	 vala hello plugins
`

**Comment by semicode-ltd** [comment]
you are using an old repo build with empty plugins clean the repo again and try now

**Comment by 0vulns** [comment]
As @semicode-ltd said, you'll need to re-clone the repo then you can build without any issues (we hope).
