### ISSUE TITLE
Contributing guide is missing

### ISSUE THREAD

**Issue by Fcmam5** [semicode-ltd/sarah#25]
As-Salam alikum.
Please brothers we'd like to contribute in this awesome project, we just need a contributing guide so we can make Sarah do more awesome things.

Thank you for wt u did, from an Algerian newbie :smile: , proud of you

**Comment by semicode-ltd** [comment]
Okay let me just make a wiki page now :)

**Comment by semicode-ltd** [comment]
check the wiki now : 
https://github.com/semicode-ltd/sarah/wiki
