### ISSUE TITLE
BeautifulSoup is not supported in Python 3

### ISSUE THREAD

**Issue by ilyeshammadi** [semicode-ltd/sarah#27]
BeautifulSoup is not supported in Python 3. the `pip install -r requirements.txt` crash when using the pip3. This dependency need to be replaced with the new version of the BeautifulSoup that is the [**BeautifulSoup4**](https://pypi.python.org/pypi/beautifulsoup4)

**Comment by semicode-ltd** [comment]
do :
pip install --upgrade beautifulsoup4

**Comment by ilyeshammadi** [comment]
Thank you 😃

**Comment by semicode-ltd** [comment]
you welcome friend :) 
did it worked for you ? so i can close the issue ?
