### ISSUE TITLE
Download Semicode OS

### ISSUE THREAD

**Issue by martinsookael** [semicode-ltd/sarah#30]
Hi! 

I know it's possibly the wrong thread (but I can't find anything for Semicode OS itself). 
I've been unable to download SemiCode OS from all of the 3 links provided, since you've gone over the quota. I hope it's all because you are doing real well. 
Nevertheless, would it be possible to download it from somewhere 4th place?

**Comment by semicode-ltd** [comment]
okay did you tried torrent link ?

**Comment by semicode-ltd** [comment]
okay did you tried torrent link ?

**Comment by martinsookael** [comment]
did not try it, i try not to have torrent software in my computer. 
If you say there are no other ways, i can try to get it this way.

**Comment by semicode-ltd** [comment]
the other way is waiting me to upload it to private ftp server and allow anonymous download and that gonna take while with my current internet connection speed
