### ISSUE TITLE
Interactive shell?

### ISSUE THREAD

**Issue by fonix232** [semicode-ltd/sarah#31]
I think it would make great sense if not just the ability to run commands was made possible, but an interactive shell was also included.

Something like this:

    $ sarah -i
    Hello! I'm Sarah, your personal assistant. To list my commands, use the command 'help'
    > watch titanic
    Name : Titanic
    Year of Releasing : 1997
    Movie or Series : movie
    Genre : Drama, Romance
    Cast : Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates
    Ok I will watch it because it got 7.7 on imdb
    > translate pencil
    قلم رصاص

It would make it also possible (or at least a lot easier) to run Sarah in a Docker container.

**Comment by semicode-ltd** [comment]
we are working on this friend thank you :)
