### ISSUE TITLE
How to install sarah in Fedora?

### ISSUE THREAD

**Issue by gaunthan** [semicode-ltd/sarah#32]
Hi.I am very interested to sarah. I can't help trying it out, but I think I need some help.
I am using Fedora instead of Ubuntu, so the current installation guide  doesn't meets my need.So here is my question:

> How to install sarah in Fedora? 

Clone the repository, then run some scripts? Or I can get a rpm package of sarah from somewhere else? 

I look forward to a reply at your convenience. Thank you.

**Comment by xen0f0n** [comment]
Hello @gaunthan , 
late answer... 
I've just installed sarah on Fedora 25! 

Install vala and libpeas
```
sudo dnf install vala
sudo dnf install libpeas-*
```
Clone the repo, cd into sarah/bin and follow the instructions in README
```
$ make
$ make install
$ export LD_LIBRARY_PATH=.
$ export GI_TYPELIB_PATH=.
$ ./sarah <some command to run>
```

**Comment by gaunthan** [comment]
Thanks! :-D

You also need to run this command in repo folder **sarah/** for installing dependent python packages
```bash
sudo pip install -r requirements.txt
```
Of course, make sure you have installed `pip`.

For running Sarah at any directory, continue to run the following commands in **sarah/bin/**

```shell
echo export LD_LIBRARY_PATH=`pwd` >> ~/.bashrc
echo export GI_TYPELIB_PATH=`pwd` >> ~/.bashrc
sudo ln $(pwd)/sarah /usr/bin/sarah -sf
```

**Comment by gaunthan** [comment]
Oh, there are many problems if running sarah in other directory...

The code is weak, it use "./plugins/" to load plugins, so you only can run `sarah` in sarah/bin/ so far.
