### ISSUE TITLE
Please update README file and change the default action of sarah.

### ISSUE THREAD

**Issue by gaunthan** [semicode-ltd/sarah#33]
Hi. 

I run `sarah help` but nothing happened. But if I run `sarah` without any param, it outputed "Help Me!"

I read the README file again and again, but doesn't find anything helpful and related to the problem. 

So I decided to read the source code, and I found this
```vala
        public void init (string[] args)                                                  
        {   
            if (args.length <= 1)
            {   
                stdout.printf ("Help Me!\n");
            }else {
                if (args[1] == "list"){
                    stdout.printf("Commands :\n");
                    plugins = manager.list(true);
                } else {
                    plugins = manager.list();
                    if (args[1] in plugins){
                        manager.run(args);
                    }
                }
            }
        }
```
It seems that we should use `sarah list` instead of `sarah help`. Yeah, `sarah list` works...

Please update README file. Simply add a TODO list will be fine.

Also, changing the default action of sarah, let `sarah` printing useful message should be more helpful. :-D

**Comment by semicode-ltd** [comment]
Done. thank you
