### ISSUE TITLE
semicode

### ISSUE THREAD

**Issue by dezzer7** [semicode-ltd/sarah#36]
is the latest version of semicode (2017/12/30) stable ?
can i use it instead of windows ?

**Comment by 0vulns** [comment]
Hi @dezzer7, SemicodeOS still unstable and current version is a beta

بتاريخ ٢٥‏/٠١‏/٢٠١٨ ٤:٣٦ م، كتب "dezzer7" <notifications@github.com>:

**Comment by 0vulns** [comment]
We're waiting for the offical version to resealed

**Comment by rykerdz** [comment]
Thanks , hope it will come up soon
