### ISSUE TITLE
can't run it

### ISSUE THREAD

**Issue by marties** [semicode-ltd/sarah#5]
under archlinux i tried python 2 2.7 3 3.5 but it gives errors about Tabs used instead of spaces, is there something i'm missing ?

python sarah.py   gives me
  File "sarah.py", line 196
    print(".py File Created Successfully , Check your Current Path")
                                                                   ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by Lerentis** [comment]
I'm running it under arch. try:
```
python2 sarah.py
```

if that does not work, change the shebang at the beginning to

```
#!/usr/bin/python2
# -*- coding: utf-8 -*-
#!/usr/bin/env python2.7
```
Also you will have to install the needed python2 packages via pip2

EDIT:
```
yaourt -S python2-beautifulsoup4
yaourt -S python2-pip
sudo pip2 install translate
sudo pip2 install omdb
sudo pip2 install wikipedia
```

**Comment by marties** [comment]
hi,
thanks for your quick answer, i ended up doing all the commands via pip2 even beautifulsoup4
with sudo pip2 install bs4
let's dive in :-)
thanks
