### ISSUE TITLE
Can you guys upload a sample py based plugin

### ISSUE THREAD

**Issue by KyleSponz** [semicode-ltd/sarah#8]
Id love to play with extending sarah, could one of you guys be awesome and upload me a python plugin so I can see how the basic structure is. I would love to contribute some!

I am very excited about this project AMAZING JOB!!!!!!

**Comment by KyleSponz** [comment]
Edit, for some reason I didnt see the hi.py plugin. Thanks so much Looking forward to collaboration!

**Comment by msupercoder** [comment]
Yes Hi is Python Plugin Example
